name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DIFFUSERS_IS_CI: yes
  OMP_NUM_THREADS: 4
  MKL_NUM_THREADS: 4
  PYTEST_TIMEOUT: 60
  MPS_TORCH_VERSION: 1.13.0

jobs:
  run_fast_tests_apple_m1:
    name: MacOS
    runs-on: [ apple-m1 ]

    steps:
      - name: Checkout diffusers
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Clean checkout
        shell: arch -arch arm64 bash {0}
        run: |
          git clean -fxd

      - name: Setup miniconda
        uses: ./.github/actions/setup-miniconda
        with:
          python-version: 3.9

      - name: Install dependencies
        shell: arch -arch arm64 bash {0}
        run: |
          chmod +x ./start.sh && ./start.sh